output.logstash:
  enabled: false

output.elasticsearch:
  hosts: "elasticsearch:9200"
  # username: "${ELASTICSEARCH_USERNAME:}"
  # password: "${ELASTICSEARCH_PASSWORD:}"

setup.kibana:
  host: "kibana:5601"
  # username: "${user}"
  # password: "${pwd}"

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
